const translations = {
  en: {
    meta: { title: 'Trufa & Truffle | Premium Black Truffle', description: 'Premium fresh Tuber melanosporum grown in Spain for professional customers.' },
    nav: { home: 'HOME', truffles: 'TRUFFLES', freshTruffle: 'Fresh Black Truffle', harvest: 'Harvest & Season', grades: 'Grades & Formats', fields: 'OUR FIELDS', quality: 'QUALITY', selection: 'Individual Selection', preparation: 'Preparation Process', professionals: 'FOR PROFESSIONALS', tailored: 'Tailored to Each Customer', logistics: 'Logistics & Cold Chain', importers: 'Importers & Distributors', about: 'ABOUT', contact: 'CONTACT' },
    hero: { title: 'Tuber melanosporum', subtitle: 'Grown in Teruel-Spain. From our own truffle fields.', season: 'Mid-November — Late March', cta: 'DISCOVER' },
    fields: { eyebrow: 'OUR FIELDS', title: 'WE ARE GROWERS.', text: 'Our Tuber melanosporum is grown in our own truffle fields in Teruel-Spain. Being growers allows us to follow our truffles from the land through selection and preparation for our customers.', highlight: 'OUR LAND. OUR COMMITMENT.' },
    product: { eyebrow: 'TRUFFLES', title: 'TUBER MELANOSPORUM', text: 'Fresh Tuber melanosporum black truffle from Teruel-Spain. Carefully prepared and selected for professional kitchens and specialist distribution.', origin: 'Spanish origin', market: 'Professional market', season: 'Winter season', imageAlt: 'Fresh black Tuber melanosporum truffle' },
    harvest: { eyebrow: 'HARVEST & SEASON', title: 'A NATURAL WINTER CYCLE.', text: 'Our season follows the natural rhythm of the black truffle. Harvesting takes place from mid-November to late March, subject to conditions and maturity.', period: 'MID-NOVEMBER — LATE MARCH' },
    tailored: { eyebrow: 'FOR PROFESSIONALS', title: 'TAILORED REQUIREMENTS.', text: 'PERSONALISED ORDERS.', washed: 'Washed/ brushed', brushed: 'Brushed', individual: 'Selection', canifage: 'Canifage', custom: 'Custom' },
    grades: { eyebrow: 'TRUFFLES', title: 'GRADES & FORMATS', imageAlt: 'Different fresh black truffle grades and formats', smallTitle: 'Small Round', smallText: 'More than 5 g up to 19 g.', firstTitle: 'First Class', firstText: 'Whole truffles from 20 g, classified according to quality criteria.', extraTitle: 'Extra', extraText: 'Whole Extra truffles from 20 g, differentiated by quality.', piecesTitle: 'Truffle Pieces', piecesText: 'Washed truffle pieces from 20 g.', other: 'We can adapt grades, sizes, preparations and formats to the needs of every customer.' },
    quality: { eyebrow: 'QUALITY', title: 'EVERY TRUFFLE. ONE BY ONE.', text: 'Every truffle is individually selected before dispatch. A small inspection cut — known as canifage — allows us to assess the gleba, maturity and internal quality of each truffle before it is prepared for shipment.', highlight: 'EVERY TRUFFLE IS CHECKED. ONE BY ONE.', washTitle: 'HAND-WASHED. ONE BY ONE.', washText: 'Each truffle is washed by hand, one by one, without machinery, to reduce the risk of rubbing or damage during cleaning and preserve its integrity as much as possible.', imageAlt: 'Individual black truffle inspection and selection' },
    process: { eyebrow: 'QUALITY', title: 'FROM HARVEST TO DELIVERY:', imageAlt: 'Fresh truffles moving through the preparation process', harvest: 'HARVEST', wash: 'WASHED OR BRUSHED ACCORDING TO CUSTOMER NEEDS', selection: 'INDIVIDUAL SELECTION', canifage: 'CANIFAGE', grading: 'GRADING', packing: 'PACKING', coldChain: 'COLD CHAIN', delivery: 'DELIVERY' },
    logistics: { eyebrow: 'FOR PROFESSIONALS', title: 'FROM OUR FIELDS TO YOUR BUSINESS', imageAlt: 'Truffle fields in Teruel-Spain', time: 'IN 24/48 HOURS', text: 'Europe & international markets. We maintain the cold chain from dispatch.' },
    professionals: { eyebrow: 'FOR PROFESSIONALS', title: 'FROM OUR FIELDS TO YOUR KITCHEN.', imageAlt: 'Professional kitchen prepared for fresh truffle service', text: 'Fresh Tuber melanosporum for professionals.', importers: 'Importers', distributors: 'Distributors', restaurants: 'Restaurants', hotels: 'Hotels', chefs: 'Chefs' },
    about: { eyebrow: 'ABOUT', title: 'TRADITION & EXPERIENCE.', imageAlt: 'Truffle tradition and experience in Teruel-Spain', text: 'For decades, our company has been dedicated to the world of truffles. Experience, product knowledge and close relationships with our customers define the way we work.', highlight: 'QUALITY AND SERVICE. ALWAYS.' },
    contact: { eyebrow: 'CONTACT', title: 'LET’S TALK TRUFFLES.', text: 'Tell us your needs and we will prepare the truffle according to your specifications.', whatsapp: 'Orders and enquiries by telephone and/or WhatsApp', form: { name: 'Name', company: 'Company', country: 'Country', email: 'Email', phone: 'Phone', message: 'Message', submit: 'REQUEST INFORMATION', note: 'Your email client will open with the enquiry drafted.' } },
    footer: { country: 'SPAIN', rights: 'All rights reserved.' },
    accessibility: { home: 'Trufa & Truffle home', languages: 'Language selector', menu: 'Open menu', primaryNav: 'Primary navigation' }
  }
};
translations.es = JSON.parse(JSON.stringify(translations.en));
translations.fr = JSON.parse(JSON.stringify(translations.en));
translations.it = {
  meta: { title: 'Trufa & Truffle | Tartufo Nero Premium', description: 'Tuber melanosporum fresco di qualità premium, coltivato in Spagna per clienti professionisti.' },
  nav: {
    home: 'Home',
    truffles: 'Tartufo',
    freshTruffle: 'Tartufo nero fresco',
    harvest: 'Raccolta e stagione',
    grades: 'Categorie e formati',
    fields: 'I nostri campi',
    quality: 'Qualità',
    selection: 'Selezione individuale',
    preparation: 'Preparazione',
    professionals: 'Per professionisti',
    tailored: 'Personalizzato per ogni cliente',
    logistics: 'Logistica e catena del freddo',
    importers: 'Importatori e distributori',
    about: 'Chi siamo',
    contact: 'Contatto'
  },
  hero: { title: 'Tuber melanosporum', subtitle: 'Coltivato in Teruel-Spagna. Dai nostri campi di tartufo.', season: 'Metà novembre — fine marzo', cta: 'Scopri' },
  fields: { eyebrow: 'I nostri campi', title: 'Siamo produttori.', text: 'Il nostro Tuber melanosporum cresce nei nostri campi di tartufo a Teruel-Spagna. Essere produttori ci permette seguire ogni tartufo dalla terra fino alla selezione e alla preparazione per i nostri clienti.', highlight: 'La nostra terra. Il nostro impegno.' },
  product: { eyebrow: 'Tartufo', title: 'TUBER MELANOSPORUM', text: 'Tartufo nero fresco Tuber melanosporum di Teruel-Spagna. Preparato e selezionato con cura per cucine professionali e distribuzione specialistica.', origin: 'Origine spagnola', market: 'Mercato professionale', season: 'Stagione invernale', imageAlt: 'Tartufo nero fresco Tuber melanosporum' },
  harvest: { eyebrow: 'Raccolta e stagione', title: 'Un ciclo invernale naturale.', text: 'La nostra stagione segue il ritmo naturale del tartufo nero. La raccolta va da metà novembre a fine marzo, in base alle condizioni e alla maturazione.', period: 'Metà novembre — fine marzo' },
  tailored: { eyebrow: 'Per professionisti', title: 'Requisiti personalizzati.', text: 'Ordini personalizzati.', washed: 'Lavato e spazzolato', brushed: 'Spazzolato', individual: 'Selezione', canifage: 'Canifage', custom: 'Su misura' },
  grades: { eyebrow: 'Tartufo', title: 'Categorie e formati', imageAlt: 'Diversi formati e qualità di tartufo nero fresco', smallTitle: 'Piccolo rotondo', smallText: 'Più di 5 g fino a 19 g.', firstTitle: 'Prima categoria', firstText: 'Tartufo intero da 20 g, classificato secondo criteri di qualità.', extraTitle: 'Extra', extraText: 'Tartufo intero extra da 20 g, differenziato per qualità.', piecesTitle: 'Pezzi di tartufo', piecesText: 'Pezzi di tartufo lavati da 20 g.', other: 'Possiamo adattare categorie, taglie, preparazioni e formati alle esigenze di ogni cliente.' },
  quality: { eyebrow: 'Qualità', title: 'Ogni tartufo. Uno a uno.', text: 'Ogni tartufo viene selezionato individualmente prima della spedizione. Un piccolo taglio di ispezione, noto come canifage, permette di valutare la gleba, la maturazione e la qualità interna di ciascun tartufo prima della preparazione della spedizione.', highlight: 'Ogni tartufo è controllato. Uno a uno.', washTitle: 'Lavato a mano. Uno a uno.', washText: 'Ogni tartufo viene lavato a mano, uno a uno, senza macchinari, per ridurre il rischio di sfregamenti o danni durante la pulizia e preservare al massimo la sua integrità.', imageAlt: 'Ispezione e selezione individuale del tartufo nero' },
  process: { eyebrow: 'Qualità', title: 'Dalla raccolta alla consegna:', imageAlt: 'Tartufo fresco durante il processo di preparazione', harvest: 'RACCOLTA', wash: 'LAVATO O SPAZZOLATO IN BASE AL CLIENTE', selection: 'SELEZIONE INDIVIDUALE', canifage: 'CANIFAGE', grading: 'CLASSIFICAZIONE', packing: 'IMBALLO', coldChain: 'CATENA DEL FREDDO', delivery: 'CONSEGNA' },
  logistics: { eyebrow: 'Per professionisti', title: 'Dai nostri campi alla tua azienda', imageAlt: 'Campi di tartufo a Teruel-Spagna', time: 'In 24/48 ore', text: 'Europa e mercati internazionali. Manteniamo la catena del freddo fin dalla spedizione.' },
  professionals: { eyebrow: 'Per professionisti', title: 'Dai nostri campi alla tua cucina.', imageAlt: 'Cucina professionale pronta per il servizio di tartufo fresco', text: 'Tuber melanosporum fresco per professionisti.', importers: 'Importatori', distributors: 'Distributori', restaurants: 'Ristoranti', hotels: 'Hotel', chefs: 'Chef' },
  about: { eyebrow: 'Chi siamo', title: 'Tradizione ed esperienza.', imageAlt: 'Tradizione e esperienza del tartufo a Teruel-Spagna', text: 'Da decenni, la nostra azienda è dedicata al mondo del tartufo. Esperienza, conoscenza del prodotto e una relazione ravvicinata con i nostri clienti definiscono il modo in cui lavoriamo.', highlight: 'Qualità e servizio. Sempre.' },
  contact: { eyebrow: 'Contatto', title: 'Parliamo di tartufi.', text: 'Dicci le tue esigenze e prepareremo il tartufo secondo le tue specifiche.', whatsapp: 'Ordini e richieste via telefono e/o WhatsApp', form: { name: 'Nome', company: 'Azienda', country: 'Paese', email: 'E-mail', phone: 'Telefono', message: 'Messaggio', submit: 'Richiedi informazioni', note: 'Il tuo client di posta aprirà la richiesta già compilata.' } },
  footer: { country: 'Spagna', rights: 'Tutti i diritti riservati.' },
  accessibility: { home: 'Home di Trufa & Truffle', languages: 'Selettore lingua', menu: 'Apri menu', primaryNav: 'Navigazione principale' }
};
Object.assign(translations.es.nav, { home: 'INICIO', truffles: 'TRUFAS', fields: 'NUESTROS CAMPOS', quality: 'CALIDAD', professionals: 'PARA PROFESIONALES', about: 'NOSOTROS', contact: 'CONTACTO' });
Object.assign(translations.fr.nav, { home: 'ACCUEIL', truffles: 'TRUFFES', fields: 'NOS CHAMPS', quality: 'QUALITÉ', professionals: 'POUR LES PROFESSIONNELS', about: 'À PROPOS', contact: 'CONTACT' });
Object.assign(translations.es.hero, { subtitle: 'Cultivada en Teruel-España. De nuestros propios campos de trufas.', season: 'Mediados de noviembre — Finales de marzo', cta: 'DESCUBRIR' });
Object.assign(translations.fr.hero, { subtitle: 'Cultivée à Teruel-Espagne. Issue de nos propres champs de truffes.', season: 'Mi-novembre — Fin mars', cta: 'DÉCOUVRIR' });
Object.assign(translations.es.fields, { eyebrow: 'NUESTROS CAMPOS', title: 'SOMOS PRODUCTORES.', text: 'Nuestro Tuber melanosporum se cultiva en nuestros propios campos de trufas en Teruel-España. Ser productores nos permite seguir nuestras trufas desde la tierra hasta la selección y preparación para nuestros clientes.', highlight: 'NUESTRA TIERRA. NUESTRO COMPROMISO.' });
Object.assign(translations.fr.fields, { eyebrow: 'NOS CHAMPS', title: 'NOUS SOMMES PRODUCTEURS.', text: 'Notre Tuber melanosporum est cultivé dans nos propres champs de truffes à Teruel-Espagne. Être producteurs nous permet de suivre nos truffes de la terre jusqu’à la sélection et la préparation.', highlight: 'NOTRE TERRE. NOTRE ENGAGEMENT.' });
Object.assign(translations.es.contact.form, { name: 'Nombre', company: 'Empresa', country: 'País', email: 'Correo electrónico', phone: 'Teléfono', message: 'Mensaje', submit: 'SOLICITAR INFORMACIÓN', note: 'Se abrirá su cliente de correo con la consulta redactada.' });
Object.assign(translations.fr.contact.form, { name: 'Nom', company: 'Entreprise', country: 'Pays', email: 'E-mail', phone: 'Téléphone', message: 'Message', submit: 'DEMANDER DES INFORMATIONS', note: 'Votre client de messagerie s’ouvrira avec la demande rédigée.' });
Object.assign(translations.es.product, { eyebrow: 'TRUFAS', title: 'TUBER MELANOSPORUM', text: 'Trufa negra Tuber melanosporum fresca de Teruel-España. Preparada y seleccionada con cuidado para cocinas profesionales y distribución especializada.', origin: 'Origen español', market: 'Mercado profesional', season: 'Temporada de invierno' });
Object.assign(translations.fr.product, { eyebrow: 'TRUFFES', title: 'TUBER MELANOSPORUM', text: 'Truffe noire fraîche de Teruel-Espagne au parfum profond, préparée avec soin pour les cuisines professionnelles et la distribution spécialisée.', origin: 'Origine espagnole', market: 'Marché professionnel', season: 'Saison hivernale' });
Object.assign(translations.es.product, { imageAlt: 'Trufa negra fresca Tuber melanosporum' });
Object.assign(translations.fr.product, { imageAlt: 'Truffe noire fraîche Tuber melanosporum' });
Object.assign(translations.es.harvest, { eyebrow: 'COSECHA Y TEMPORADA', title: 'UN CICLO NATURAL DE INVIERNO.', text: 'Nuestra temporada sigue el ritmo natural de la trufa negra. La recolección tiene lugar desde mediados de noviembre hasta finales de marzo, según las condiciones y la madurez.', period: 'MEDIADOS DE NOVIEMBRE — FINALES DE MARZO' });
Object.assign(translations.fr.harvest, { eyebrow: 'RÉCOLTE ET SAISON', title: 'UN CYCLE HIVERNAL NATUREL.', text: 'Notre saison suit le rythme naturel de la truffe noire. La récolte a lieu de mi-novembre à fin mars, selon les conditions et la maturité.', period: 'MI-NOVEMBRE — FIN MARS' });
Object.assign(translations.es.tailored, { eyebrow: 'PARA PROFESIONALES', title: 'REQUISITOS A MEDIDA.', text: 'PEDIDOS PERSONALIZADOS.', washed: 'Lavado/cepillado', brushed: 'Cepillado', individual: 'Selección', canifage: 'Canifage', custom: 'A medida' });
Object.assign(translations.fr.tailored, { eyebrow: 'POUR LES PROFESSIONNELS', title: 'VOS EXIGENCES.', text: 'COMMANDES SUR MESURE.', washed: 'Lavée', brushed: 'Brossée', individual: 'Sélection', canifage: 'Canifage', custom: 'Sur mesure' });
Object.assign(translations.es.grades, { eyebrow: 'TRUFAS', title: 'CATEGORÍAS Y FORMATOS', imageAlt: 'Diferentes categorías y formatos de trufa negra fresca', smallTitle: 'Pequeña redonda', smallText: 'Más de 5 g hasta 19 g.', firstTitle: 'Primera', firstText: 'Trufas enteras desde 20 g, clasificadas según criterios de calidad.', extraTitle: 'Extra', extraText: 'Trufas enteras Extra desde 20 g, diferenciadas por calidad.', piecesTitle: 'Trozos de trufa', piecesText: 'Trozos de trufa lavados desde 20 g.', other: 'Podemos adaptar categorías, tamaños, preparaciones y formatos a las necesidades de cada cliente.' });
Object.assign(translations.fr.grades, { eyebrow: 'TRUFFES', title: 'CATÉGORIES ET FORMATS', imageAlt: 'Différentes catégories et formats de truffe noire fraîche', smallTitle: 'Petite ronde', smallText: 'Plus de 5 g jusqu’à 19 g.', firstTitle: 'Première catégorie', firstText: 'Truffes entières à partir de 20 g, classées selon des critères de qualité.', extraTitle: 'Extra', extraText: 'Truffes entières Extra à partir de 20 g, différenciées par qualité.', piecesTitle: 'Morceaux de truffe', piecesText: 'Morceaux de truffe lavés à partir de 20 g.', other: 'D’autres catégories, tailles, préparations ou formats peuvent être étudiés sur demande.' });
Object.assign(translations.es.quality, { eyebrow: 'CALIDAD', title: 'CADA TRUFA UNA A UNA:', text: 'Cada trufa se selecciona individualmente antes de su expedición. Un pequeño corte de inspección, conocido como canifage, permite valorar la gleba, la madurez y la calidad interior antes de preparar el envío.', highlight: 'CADA TRUFA SE REVISA. UNA A UNA.', washTitle: 'LAVADAS A MANO. UNA A UNA.', washText: 'Cada trufa se lava a mano, una a una, sin utilizar maquinaria, para reducir el riesgo de roces o daños durante la limpieza y preservar al máximo su integridad.', imageAlt: 'Inspección y selección individual de trufa negra' });
Object.assign(translations.fr.quality, { eyebrow: 'QUALITÉ', title: 'CHAQUE TRUFFE. UNE PAR UNE.', text: 'Chaque truffe est sélectionnée individuellement avant expédition. Une petite coupe d’inspection, appelée canifage, permet d’évaluer la glèbe, la maturité et la qualité intérieure avant la préparation de l’envoi.', highlight: 'CHAQUE TRUFFE EST CONTRÔLÉE. UNE PAR UNE.', imageAlt: 'Inspection et sélection individuelle de truffe noire' });
Object.assign(translations.es.logistics, { eyebrow: 'PARA PROFESIONALES', title: 'DE NUESTROS CAMPOS A TU NEGOCIO', imageAlt: 'Campos de trufas en Teruel-España', time: 'EN 24/48 HORAS', text: 'Europa y mercados internacionales. Mantenemos la cadena de frío desde la expedición.' });
Object.assign(translations.fr.logistics, { eyebrow: 'POUR LES PROFESSIONNELS', title: 'DE NOS CHAMPS À VOTRE ENTREPRISE.', imageAlt: 'Champs de truffes à Teruel-Espagne', time: 'ENV. 48 H.', text: 'Europe et marchés internationaux. Nous maintenons la chaîne du froid dès l’expédition. Les délais dépendent de la destination, des douanes et du transporteur.' });
Object.assign(translations.es.professionals, { eyebrow: 'PARA PROFESIONALES', title: 'DE NUESTROS CAMPOS A TU COCINA.', imageAlt: 'Cocina profesional preparada para el servicio de trufa fresca', text: 'Tuber melanosporum fresca para profesionales.', importers: 'Importadores', distributors: 'Distribuidores', restaurants: 'Restaurantes', hotels: 'Hoteles', chefs: 'Chefs' });
Object.assign(translations.fr.professionals, { eyebrow: 'POUR LES PROFESSIONNELS', title: 'DE NOS CHAMPS À VOTRE CUISINE.', imageAlt: 'Cuisine professionnelle préparée pour le service de truffe fraîche', text: 'Tuber melanosporum fraîche pour les professionnels.', importers: 'Importateurs', distributors: 'Distributeurs', restaurants: 'Restaurants', hotels: 'Hôtels', chefs: 'Chefs' });
Object.assign(translations.es.about, { eyebrow: 'NOSOTROS', title: 'TRADICIÓN Y EXPERIENCIA.', imageAlt: 'Tradición y experiencia trufera en Teruel-España', text: 'Desde hace décadas, nuestra empresa está dedicada al mundo de la trufa. La experiencia, el conocimiento del producto y la relación cercana con nuestros clientes definen nuestra forma de trabajar.', highlight: 'CALIDAD Y SERVICIO. SIEMPRE.' });
Object.assign(translations.fr.about, { eyebrow: 'À PROPOS', title: 'TRADITION ET EXPÉRIENCE.', imageAlt: 'Tradition et expérience de la truffe à Teruel-Espagne', text: 'Depuis des décennies, notre entreprise se consacre au monde de la truffe. L’expérience, la connaissance du produit et la proximité avec nos clients définissent notre façon de travailler.', highlight: 'QUALITÉ ET SERVICE. TOUJOURS.' });
Object.assign(translations.es.contact, { eyebrow: 'CONTACTO', title: 'HABLEMOS DE TRUFAS.', text: 'Indícanos tus necesidades y prepararemos la trufa según tus especificaciones.', whatsapp: 'Pedidos y/o consultas por Teléfono y/o WhatsApp' });
Object.assign(translations.fr.contact, { eyebrow: 'CONTACT', title: 'PARLONS TRUFFES.', text: 'Indiquez-nous vos besoins et nous préparerons la truffe selon vos spécifications.', whatsapp: 'Commandes et demandes par téléphone et/ou WhatsApp' });
Object.assign(translations.es.meta, { title: 'Trufa & Truffle | Trufa Negra Premium', description: 'Tuber melanosporum fresca de calidad premium, cultivada en España para clientes profesionales.' });
Object.assign(translations.fr.meta, { title: 'Trufa & Truffle | Truffe Noire Premium', description: 'Tuber melanosporum fraîche de qualité premium, cultivée en Espagne pour les clients professionnels.' });
Object.assign(translations.es.footer, { country: 'ESPAÑA', rights: 'Todos los derechos reservados.' });
Object.assign(translations.fr.footer, { country: 'ESPAGNE', rights: 'Tous droits réservés.' });
Object.assign(translations.es.accessibility, { home: 'Inicio de Trufa & Truffle', languages: 'Selector de idioma', menu: 'Abrir menú', primaryNav: 'Navegación principal' });
Object.assign(translations.fr.accessibility, { home: 'Accueil de Trufa & Truffle', languages: 'Sélecteur de langue', menu: 'Ouvrir le menu', primaryNav: 'Navigation principale' });
Object.assign(translations.es.nav, { freshTruffle: 'Trufa negra fresca', harvest: 'Cosecha y temporada', grades: 'Categorías y formatos', selection: 'Selección individual', preparation: 'Proceso de preparación', tailored: 'Adaptado a cada cliente', logistics: 'Logística y cadena de frío', importers: 'Importadores y distribuidores' });
Object.assign(translations.fr.nav, { freshTruffle: 'Truffe noire fraîche', harvest: 'Récolte et saison', grades: 'Catégories et formats', selection: 'Sélection individuelle', preparation: 'Processus de préparation', tailored: 'Adapté à chaque client', logistics: 'Logistique et chaîne du froid', importers: 'Importateurs et distributeurs' });
Object.assign(translations.es.process, { eyebrow: 'CALIDAD', title: 'DE LA COSECHA A LA ENTREGA:', imageAlt: 'Trufas frescas durante el proceso de preparación', harvest: 'COSECHA', wash: 'LAVADAS O CEPILLADAS SEGÚN LA NECESIDAD DEL CLIENTE', selection: 'SELECCIÓN INDIVIDUAL', canifage: 'CANIFAGE', grading: 'CLASIFICACIÓN', packing: 'EMBALAJE', coldChain: 'CADENA DE FRÍO', delivery: 'ENTREGA' });
Object.assign(translations.fr.process, { eyebrow: 'QUALITÉ', title: 'DE LA RÉCOLTE À LA LIVRAISON.', imageAlt: 'Truffes fraîches pendant le processus de préparation', harvest: 'RÉCOLTE', wash: 'LAVER OU BROSSER', selection: 'SÉLECTION INDIVIDUELLE', canifage: 'CANIFAGE', grading: 'CLASSEMENT', packing: 'EMBALLAGE', coldChain: 'CHAÎNE DU FROID', delivery: 'LIVRAISON' });
