const translations = {
  en: {
    meta: { title: 'Trufa & Truffle | Premium Black Truffle', description: 'Premium fresh Tuber melanosporum grown in Spain for professional customers.' },
    nav: { home: 'HOME', truffles: 'TRUFFLES', freshTruffle: 'Fresh Black Truffle', harvest: 'Harvest & Season', grades: 'Grades & Formats', fields: 'OUR FIELDS', quality: 'QUALITY', selection: 'Individual Selection', preparation: 'Preparation Process', professionals: 'FOR PROFESSIONALS', tailored: 'Tailored to Each Customer', logistics: 'Logistics & Cold Chain', importers: 'Importers & Distributors', about: 'ABOUT', contact: 'CONTACT' },
    hero: { eyebrow: 'FRESH BLACK TRUFFLE', title: 'Tuber melanosporum', subtitle: 'Grown in Spain. From our own truffle fields.', season: 'Mid-November — Late March', cta: 'DISCOVER' },
    fields: { eyebrow: 'OUR FIELDS', title: 'WE ARE GROWERS.', text: 'Our Tuber melanosporum is grown in our own truffle fields in Spain. Being growers allows us to follow our truffles from the land through selection and preparation for our customers.', highlight: 'OUR LAND. OUR COMMITMENT.' },
    product: { eyebrow: 'TRUFFLES', title: 'TUBER MELANOSPORUM', text: 'Fresh Spanish black truffle with a deep aroma, carefully prepared for professional kitchens and specialist distribution.', origin: 'Spanish origin', market: 'Professional market', season: 'Winter season', imageAlt: 'Fresh black Tuber melanosporum truffle' },
    harvest: { eyebrow: 'HARVEST & SEASON', title: 'A NATURAL WINTER CYCLE.', text: 'Our season follows the natural rhythm of the black truffle. Harvesting takes place from mid-November to late March, subject to conditions and maturity.', period: 'MID-NOVEMBER — LATE MARCH' },
    tailored: { eyebrow: 'FOR PROFESSIONALS', title: 'YOUR REQUIREMENTS. OUR SELECTION.', text: 'Fresh Tuber melanosporum prepared according to your requirements.', washed: 'Washed', brushed: 'Brushed', individual: 'Individual selection', canifage: 'Canifage', custom: 'Custom requirements' },
    grades: { eyebrow: 'TRUFFLES', title: 'GRADES & FORMATS', imageAlt: 'Different fresh black truffle grades and formats', smallTitle: 'Small Round', smallText: 'More than 5 g up to 19 g.', firstTitle: 'First Class', firstText: 'Whole truffles from 20 g, classified according to quality criteria.', extraTitle: 'Extra', extraText: 'Whole Extra truffles from 20 g, differentiated by quality.', piecesTitle: 'Truffle Pieces', piecesText: 'Washed truffle pieces from 20 g.', other: 'Other grades, sizes, preparations or formats can be studied on request.' },
    quality: { eyebrow: 'QUALITY', title: 'EVERY TRUFFLE. ONE BY ONE.', text: 'Every truffle is individually selected before dispatch. A small inspection cut — known as canifage — allows us to assess the gleba, maturity and internal quality of each truffle before it is prepared for shipment.', highlight: 'EVERY TRUFFLE IS CHECKED. ONE BY ONE.', imageAlt: 'Individual black truffle inspection and selection' },
    process: { eyebrow: 'QUALITY', title: 'FROM HARVEST TO DELIVERY.', imageAlt: 'Fresh truffles moving through the preparation process', harvest: 'HARVEST', wash: 'WASH OR BRUSH', selection: 'INDIVIDUAL SELECTION', canifage: 'CANIFAGE', grading: 'GRADING', packing: 'PACKING', coldChain: 'COLD CHAIN', delivery: 'DELIVERY' },
    logistics: { eyebrow: 'FOR PROFESSIONALS', title: 'FROM OUR FIELDS TO YOUR BUSINESS.', imageAlt: 'Truffle fields in Spain', time: 'APPROX. 48H.', text: 'Europe & international markets. We maintain the cold chain from dispatch. Times depend on destination, customs and transport service.' },
    professionals: { eyebrow: 'FOR PROFESSIONALS', title: 'FROM OUR FIELDS TO YOUR KITCHEN.', imageAlt: 'Professional kitchen prepared for fresh truffle service', text: 'Fresh Tuber melanosporum for professionals.', importers: 'Importers', distributors: 'Distributors', restaurants: 'Restaurants', hotels: 'Hotels', chefs: 'Chefs' },
    about: { eyebrow: 'ABOUT', title: 'TRADITION & EXPERIENCE.', imageAlt: 'Truffle tradition and experience in Spain', text: 'For decades, our company has been dedicated to the world of truffles. Experience, product knowledge and close relationships with our customers define the way we work.', highlight: 'QUALITY AND SERVICE. ALWAYS.' },
    contact: { eyebrow: 'CONTACT', title: 'LET’S TALK TRUFFLES.', text: 'Tell us about your requirements and our team will respond with the right format for your business.', form: { name: 'Name', company: 'Company', country: 'Country', email: 'Email', phone: 'Phone', message: 'Message', submit: 'REQUEST INFORMATION', note: 'Your email client will open with the enquiry drafted.' } },
    footer: { country: 'SPAIN', rights: 'All rights reserved.' },
    accessibility: { home: 'Trufa & Truffle home', languages: 'Language selector', menu: 'Open menu', primaryNav: 'Primary navigation' }
  }
};
translations.es = JSON.parse(JSON.stringify(translations.en));
translations.fr = JSON.parse(JSON.stringify(translations.en));
Object.assign(translations.es.nav, { home: 'INICIO', truffles: 'TRUFAS', fields: 'NUESTROS CAMPOS', quality: 'CALIDAD', professionals: 'PARA PROFESIONALES', about: 'NOSOTROS', contact: 'CONTACTO' });
Object.assign(translations.fr.nav, { home: 'ACCUEIL', truffles: 'TRUFFES', fields: 'NOS CHAMPS', quality: 'QUALITÉ', professionals: 'POUR LES PROFESSIONNELS', about: 'À PROPOS', contact: 'CONTACT' });
Object.assign(translations.es.hero, { eyebrow: 'TRUFA NEGRA FRESCA', subtitle: 'Cultivada en España. De nuestros propios campos de trufas.', season: 'Mediados de noviembre — Finales de marzo', cta: 'DESCUBRIR' });
Object.assign(translations.fr.hero, { eyebrow: 'TRUFFE NOIRE FRAÎCHE', subtitle: 'Cultivée en Espagne. Issue de nos propres champs de truffes.', season: 'Mi-novembre — Fin mars', cta: 'DÉCOUVRIR' });
Object.assign(translations.es.fields, { eyebrow: 'NUESTROS CAMPOS', title: 'SOMOS PRODUCTORES.', text: 'Nuestro Tuber melanosporum se cultiva en nuestros propios campos de trufas en España. Ser productores nos permite seguir nuestras trufas desde la tierra hasta la selección y preparación para nuestros clientes.', highlight: 'NUESTRA TIERRA. NUESTRO COMPROMISO.' });
Object.assign(translations.fr.fields, { eyebrow: 'NOS CHAMPS', title: 'NOUS SOMMES PRODUCTEURS.', text: 'Notre Tuber melanosporum est cultivé dans nos propres champs de truffes en Espagne. Être producteurs nous permet de suivre nos truffes de la terre jusqu’à la sélection et la préparation.', highlight: 'NOTRE TERRE. NOTRE ENGAGEMENT.' });
Object.assign(translations.es.contact.form, { name: 'Nombre', company: 'Empresa', country: 'País', email: 'Correo electrónico', phone: 'Teléfono', message: 'Mensaje', submit: 'SOLICITAR INFORMACIÓN', note: 'Se abrirá su cliente de correo con la consulta redactada.' });
Object.assign(translations.fr.contact.form, { name: 'Nom', company: 'Entreprise', country: 'Pays', email: 'E-mail', phone: 'Téléphone', message: 'Message', submit: 'DEMANDER DES INFORMATIONS', note: 'Votre client de messagerie s’ouvrira avec la demande rédigée.' });
Object.assign(translations.es.product, { eyebrow: 'TRUFAS', title: 'TUBER MELANOSPORUM', text: 'Trufa negra fresca española, de aroma profundo, preparada con cuidado para cocinas profesionales y distribución especializada.', origin: 'Origen español', market: 'Mercado profesional', season: 'Temporada de invierno' });
Object.assign(translations.fr.product, { eyebrow: 'TRUFFES', title: 'TUBER MELANOSPORUM', text: 'Truffe noire fraîche espagnole au parfum profond, préparée avec soin pour les cuisines professionnelles et la distribution spécialisée.', origin: 'Origine espagnole', market: 'Marché professionnel', season: 'Saison hivernale' });
Object.assign(translations.es.product, { imageAlt: 'Trufa negra fresca Tuber melanosporum' });
Object.assign(translations.fr.product, { imageAlt: 'Truffe noire fraîche Tuber melanosporum' });
Object.assign(translations.es.harvest, { eyebrow: 'COSECHA Y TEMPORADA', title: 'UN CICLO NATURAL DE INVIERNO.', text: 'Nuestra temporada sigue el ritmo natural de la trufa negra. La recolección tiene lugar desde mediados de noviembre hasta finales de marzo, según las condiciones y la madurez.', period: 'MEDIADOS DE NOVIEMBRE — FINALES DE MARZO' });
Object.assign(translations.fr.harvest, { eyebrow: 'RÉCOLTE ET SAISON', title: 'UN CYCLE HIVERNAL NATUREL.', text: 'Notre saison suit le rythme naturel de la truffe noire. La récolte a lieu de mi-novembre à fin mars, selon les conditions et la maturité.', period: 'MI-NOVEMBRE — FIN MARS' });
Object.assign(translations.es.tailored, { eyebrow: 'PARA PROFESIONALES', title: 'TUS REQUISITOS. NUESTRA SELECCIÓN.', text: 'Tuber melanosporum fresca preparada según tus requisitos.', washed: 'Lavada', brushed: 'Cepillada', individual: 'Selección individual', canifage: 'Canifage', custom: 'Requisitos a medida' });
Object.assign(translations.fr.tailored, { eyebrow: 'POUR LES PROFESSIONNELS', title: 'VOS EXIGENCES. NOTRE SÉLECTION.', text: 'Tuber melanosporum fraîche préparée selon vos exigences.', washed: 'Lavée', brushed: 'Brossée', individual: 'Sélection individuelle', canifage: 'Canifage', custom: 'Exigences sur mesure' });
Object.assign(translations.es.grades, { eyebrow: 'TRUFAS', title: 'CATEGORÍAS Y FORMATOS', imageAlt: 'Diferentes categorías y formatos de trufa negra fresca', smallTitle: 'Pequeña redonda', smallText: 'Más de 5 g hasta 19 g.', firstTitle: 'Primera', firstText: 'Trufas enteras desde 20 g, clasificadas según criterios de calidad.', extraTitle: 'Extra', extraText: 'Trufas enteras Extra desde 20 g, diferenciadas por calidad.', piecesTitle: 'Trozos de trufa', piecesText: 'Trozos de trufa lavados desde 20 g.', other: 'Podemos estudiar otras categorías, tamaños, preparaciones o formatos bajo consulta.' });
Object.assign(translations.fr.grades, { eyebrow: 'TRUFFES', title: 'CATÉGORIES ET FORMATS', imageAlt: 'Différentes catégories et formats de truffe noire fraîche', smallTitle: 'Petite ronde', smallText: 'Plus de 5 g jusqu’à 19 g.', firstTitle: 'Première catégorie', firstText: 'Truffes entières à partir de 20 g, classées selon des critères de qualité.', extraTitle: 'Extra', extraText: 'Truffes entières Extra à partir de 20 g, différenciées par qualité.', piecesTitle: 'Morceaux de truffe', piecesText: 'Morceaux de truffe lavés à partir de 20 g.', other: 'D’autres catégories, tailles, préparations ou formats peuvent être étudiés sur demande.' });
Object.assign(translations.es.quality, { eyebrow: 'CALIDAD', title: 'CADA TRUFA. UNA A UNA.', text: 'Cada trufa se selecciona individualmente antes de su expedición. Un pequeño corte de inspección, conocido como canifage, permite valorar la gleba, la madurez y la calidad interior antes de preparar el envío.', highlight: 'CADA TRUFA SE REVISA. UNA A UNA.', imageAlt: 'Inspección y selección individual de trufa negra' });
Object.assign(translations.fr.quality, { eyebrow: 'QUALITÉ', title: 'CHAQUE TRUFFE. UNE PAR UNE.', text: 'Chaque truffe est sélectionnée individuellement avant expédition. Une petite coupe d’inspection, appelée canifage, permet d’évaluer la glèbe, la maturité et la qualité intérieure avant la préparation de l’envoi.', highlight: 'CHAQUE TRUFFE EST CONTRÔLÉE. UNE PAR UNE.', imageAlt: 'Inspection et sélection individuelle de truffe noire' });
Object.assign(translations.es.logistics, { eyebrow: 'PARA PROFESIONALES', title: 'DE NUESTROS CAMPOS A TU NEGOCIO.', imageAlt: 'Campos de trufas en España', time: 'APROX. 48 H.', text: 'Europa y mercados internacionales. Mantenemos la cadena de frío desde la expedición. Los tiempos dependen del destino, las aduanas y el servicio de transporte.' });
Object.assign(translations.fr.logistics, { eyebrow: 'POUR LES PROFESSIONNELS', title: 'DE NOS CHAMPS À VOTRE ENTREPRISE.', imageAlt: 'Champs de truffes en Espagne', time: 'ENV. 48 H.', text: 'Europe et marchés internationaux. Nous maintenons la chaîne du froid dès l’expédition. Les délais dépendent de la destination, des douanes et du transporteur.' });
Object.assign(translations.es.professionals, { eyebrow: 'PARA PROFESIONALES', title: 'DE NUESTROS CAMPOS A TU COCINA.', imageAlt: 'Cocina profesional preparada para el servicio de trufa fresca', text: 'Tuber melanosporum fresca para profesionales.', importers: 'Importadores', distributors: 'Distribuidores', restaurants: 'Restaurantes', hotels: 'Hoteles', chefs: 'Chefs' });
Object.assign(translations.fr.professionals, { eyebrow: 'POUR LES PROFESSIONNELS', title: 'DE NOS CHAMPS À VOTRE CUISINE.', imageAlt: 'Cuisine professionnelle préparée pour le service de truffe fraîche', text: 'Tuber melanosporum fraîche pour les professionnels.', importers: 'Importateurs', distributors: 'Distributeurs', restaurants: 'Restaurants', hotels: 'Hôtels', chefs: 'Chefs' });
Object.assign(translations.es.about, { eyebrow: 'NOSOTROS', title: 'TRADICIÓN Y EXPERIENCIA.', imageAlt: 'Tradición y experiencia trufera en España', text: 'Desde hace décadas, nuestra empresa está dedicada al mundo de la trufa. La experiencia, el conocimiento del producto y la relación cercana con nuestros clientes definen nuestra forma de trabajar.', highlight: 'CALIDAD Y SERVICIO. SIEMPRE.' });
Object.assign(translations.fr.about, { eyebrow: 'À PROPOS', title: 'TRADITION ET EXPÉRIENCE.', imageAlt: 'Tradition et expérience de la truffe en Espagne', text: 'Depuis des décennies, notre entreprise se consacre au monde de la truffe. L’expérience, la connaissance du produit et la proximité avec nos clients définissent notre façon de travailler.', highlight: 'QUALITÉ ET SERVICE. TOUJOURS.' });
Object.assign(translations.es.contact, { eyebrow: 'CONTACTO', title: 'HABLEMOS DE TRUFAS.', text: 'Cuéntanos tus requisitos y nuestro equipo responderá con el formato adecuado para tu negocio.' });
Object.assign(translations.fr.contact, { eyebrow: 'CONTACT', title: 'PARLONS TRUFFES.', text: 'Parlez-nous de vos besoins et notre équipe vous répondra avec le format adapté à votre activité.' });
Object.assign(translations.es.meta, { title: 'Trufa & Truffle | Trufa Negra Premium', description: 'Tuber melanosporum fresca de calidad premium, cultivada en España para clientes profesionales.' });
Object.assign(translations.fr.meta, { title: 'Trufa & Truffle | Truffe Noire Premium', description: 'Tuber melanosporum fraîche de qualité premium, cultivée en Espagne pour les clients professionnels.' });
Object.assign(translations.es.footer, { country: 'ESPAÑA', rights: 'Todos los derechos reservados.' });
Object.assign(translations.fr.footer, { country: 'ESPAGNE', rights: 'Tous droits réservés.' });
Object.assign(translations.es.accessibility, { home: 'Inicio de Trufa & Truffle', languages: 'Selector de idioma', menu: 'Abrir menú', primaryNav: 'Navegación principal' });
Object.assign(translations.fr.accessibility, { home: 'Accueil de Trufa & Truffle', languages: 'Sélecteur de langue', menu: 'Ouvrir le menu', primaryNav: 'Navigation principale' });
Object.assign(translations.es.nav, { freshTruffle: 'Trufa negra fresca', harvest: 'Cosecha y temporada', grades: 'Categorías y formatos', selection: 'Selección individual', preparation: 'Proceso de preparación', tailored: 'Adaptado a cada cliente', logistics: 'Logística y cadena de frío', importers: 'Importadores y distribuidores' });
Object.assign(translations.fr.nav, { freshTruffle: 'Truffe noire fraîche', harvest: 'Récolte et saison', grades: 'Catégories et formats', selection: 'Sélection individuelle', preparation: 'Processus de préparation', tailored: 'Adapté à chaque client', logistics: 'Logistique et chaîne du froid', importers: 'Importateurs et distributeurs' });
Object.assign(translations.es.process, { eyebrow: 'CALIDAD', title: 'DE LA COSECHA A LA ENTREGA.', imageAlt: 'Trufas frescas durante el proceso de preparación', harvest: 'COSECHA', wash: 'LAVAR O CEPILLAR', selection: 'SELECCIÓN INDIVIDUAL', canifage: 'CANIFAGE', grading: 'CLASIFICACIÓN', packing: 'EMBALAJE', coldChain: 'CADENA DE FRÍO', delivery: 'ENTREGA' });
Object.assign(translations.fr.process, { eyebrow: 'QUALITÉ', title: 'DE LA RÉCOLTE À LA LIVRAISON.', imageAlt: 'Truffes fraîches pendant le processus de préparation', harvest: 'RÉCOLTE', wash: 'LAVER OU BROSSER', selection: 'SÉLECTION INDIVIDUELLE', canifage: 'CANIFAGE', grading: 'CLASSEMENT', packing: 'EMBALLAGE', coldChain: 'CHAÎNE DU FROID', delivery: 'LIVRAISON' });
